version: '3.8'
services:
      
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - '5000:5000'
    volumes:
      - ./uploads:/app/images
    environment:
      - UPLOAD_FOLDER=/app/uploads
    networks:
      - my_network
  
networks:
  my_network:
    external: true
