version: '3.8'
services:

  frontend:
    image: ghcr.io/${{ github.repository }}/frontend:latest
    restart: always
    networks:
      - my_network

  api:
    image: ghcr.io/baguettetropcuite/cleanwalk-org-v2/api:latest
    volumes:
      - ./uploads:/app/uploads
    restart: always
    networks:
      - my_network

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data-nginx:/data
      - ./letsencrypt:/etc/letsencrypt
      - ./uploads:/var/www/uploads
    networks:
      - my_network

networks:
  my_network:
    external: true
