version: '3.8'
services:

  frontend:
    build: 
      context: ./front
      dockerfile: Dockerfile
    restart: always
    networks:
      - my_network
      
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    restart: always
    environment:
      - UPLOAD_FOLDER=/app/uploads
    networks:
      - my_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./uploads:/usr/share/nginx/html/uploads
    ports:
      - "80:80"
      - "443:443"
    networks:
      - my_network
  
networks:
  my_network:
    external: true
