name: Deploy to VPS

on:
  push:
    branches:
      - release # Déclencher le déploiement uniquement sur la branche release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SECRET_KEY }}  # Utilisation de la clé SSH

    - name: Deploy to VPS
      env:
        VPS_IP: ${{ secrets.VPS_IP }}
      run: |
        ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$VPS_IP '
          cd /home/cleanwalk-org-v2 &&
          git pull origin release &&
          docker compose -f docker-compose.prod.yml down &&
          docker compose -f docker-compose.prod.yml up -d --build
        '
